/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { Alert } from '@mui/material';
import { styled } from '@mui/material/styles';

 
const Frame21 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `138px 213px`,  
  boxSizing: `border-box`,  
});
  
const AlertFilled = styled(Alert)({  
  width: `320px`,  
  margin: `0px`,  
});
 
function Frame2(props) {
  return (
    <Frame21 >
       <AlertFilled variant="filled" severity={"success"}   > Alert content </AlertFilled>
       </Frame21>
   );
}

export default Frame2;
