/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { Alert } from '@mui/material';
import { styled } from '@mui/material/styles';

 
const Frame41 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: `694px`,  
  height: `403px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
});
  
const Alert521 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `362px`,  
  height: `88px`,  
  left: `0px`,  
  top: `0px`,  
  overflow: `hidden`,  
});
  
const AlertFilled = styled(Alert)({  
  width: `320px`,  
  position: `absolute`,  
  left: `16px`,  
  top: `19px`,  
});
 
function Frame4(props) {
  return (
    <Frame41 >
       <Alert521 >
         <AlertFilled variant="filled" severity={"error"}   > Alert content </AlertFilled>
         </Alert521>
     </Frame41>
   );
}

export default Frame4;
