/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { SvgIcon, Button } from '@mui/material';
import { ReactComponent as StarBorderFilled1 } from './assets/images/StarBorderFilled.svg';
import { styled } from '@mui/material/styles';
import { SampleCardProps } from './types';
import useSampleCard from './useSampleCard';
 
const TypeQuest: any = styled("div")(({ theme }: any) =>({  
  backgroundColor: theme.palette["Background"]["Default"],  
  boxShadow: `0px 4px 6px rgba(3, 0, 161, 0.2)`,  
  borderRadius: `8px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: `682px`,  
  height: `465px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
}));
  
const Image: any = styled("div", {
    shouldForwardProp: prop => !["props"].includes(prop.toString())
  })(({ props }: any) =>({  
  backgroundImage: `url(${ImageImage})`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  alignSelf: `stretch`,  
  width: `290px`,  
  margin: `0px`,  
  overflow: `hidden`,  
  backgroundImage: props.hotel.image,  
}));
  
const TextButton: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `40px 40px 0px 28px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  width: `370px`,  
  margin: `0px 0px 0px 22px`,  
});
  
const Content: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const About: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Label: any = styled("div")({  
  borderRadius: `100px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const Container: any = styled("div")(({ theme }: any) =>({  
  backgroundColor: theme.palette["Info"]["Main"],  
  borderRadius: `16px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `4px`,  
  boxSizing: `border-box`,  
  height: `28px`,  
  margin: `0px`,  
}));
  
const Typography: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `3px 6px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const Label1: any = styled("div")(({ theme }: any) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: theme.palette["Secondary"]["Contrast"],  
  fontStyle: theme.typography["Components"]["Chip"].fontStyle,  
  fontFamily: theme.typography["Components"]["Chip"].fontFamily,  
  fontWeight: theme.typography["Components"]["Chip"].fontWeight,  
  fontSize: theme.typography["Components"]["Chip"].fontSize,  
  letterSpacing: theme.typography["Components"]["Chip"].letterSpacing,  
  textDecoration: theme.typography["Components"]["Chip"].textDecoration,  
  lineHeight: theme.typography["Components"]["Chip"].lineHeight,  
  textTransform: theme.typography["Components"]["Chip"].textTransform,  
  margin: `0px`,  
}));
  
const HotelName: any = styled("div")(({ theme }: any) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: theme.palette["Text"]["Secondary"],  
  fontStyle: `normal`,  
  fontFamily: `Roboto`,  
  fontWeight: `400`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  margin: `0px 0px 0px 10px`,  
}));
  
const Details: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `28px 0px 0px 0px`,  
});
  
const Title: any = styled("div")(({ theme }: any) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: theme.palette["Text"]["Primary"],  
  fontStyle: `normal`,  
  fontFamily: `Roboto`,  
  fontWeight: `700`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
}));
  
const Price: any = styled("div")(({ theme }: any) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: theme.palette["Text"]["Secondary"],  
  fontStyle: theme.typography["Typography"]["Body 1"].fontStyle,  
  fontFamily: theme.typography["Typography"]["Body 1"].fontFamily,  
  fontWeight: theme.typography["Typography"]["Body 1"].fontWeight,  
  fontSize: theme.typography["Typography"]["Body 1"].fontSize,  
  letterSpacing: theme.typography["Typography"]["Body 1"].letterSpacing,  
  textDecoration: theme.typography["Typography"]["Body 1"].textDecoration,  
  lineHeight: theme.typography["Typography"]["Body 1"].lineHeight,  
  textTransform: theme.typography["Typography"]["Body 1"].textTransform,  
  alignSelf: `stretch`,  
  margin: `0px`,  
}));
  
const Rating: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `28px 0px 0px 0px`,  
});
  
const Icon1: any = styled(SvgIcon)(({ theme }: any) =>({  
  color: theme.palette["Action"]["Active (54p)"],  
  margin: `0px`,  
}));
  
const Rating1: any = styled("div")(({ theme }: any) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: theme.palette["Text"]["Secondary"],  
  fontStyle: theme.typography["Typography"]["Body 1"].fontStyle,  
  fontFamily: theme.typography["Typography"]["Body 1"].fontFamily,  
  fontWeight: theme.typography["Typography"]["Body 1"].fontWeight,  
  fontSize: theme.typography["Typography"]["Body 1"].fontSize,  
  letterSpacing: theme.typography["Typography"]["Body 1"].letterSpacing,  
  textDecoration: theme.typography["Typography"]["Body 1"].textDecoration,  
  lineHeight: theme.typography["Typography"]["Body 1"].lineHeight,  
  textTransform: theme.typography["Typography"]["Body 1"].textTransform,  
  flexGrow: `1`,  
  height: `21px`,  
  margin: `0px 0px 0px 6px`,  
}));
  
const Description: any = styled("div")(({ theme }: any) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: theme.palette["Text"]["Primary"],  
  fontStyle: `normal`,  
  fontFamily: `Roboto`,  
  fontWeight: `400`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `28px 0px 0px 0px`,  
}));
  
const ButtonClicked: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(25, 118, 210, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `700`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  height: `48px`,  
  width: `138px`,  
  margin: `28px 0px 0px 0px`,  
});
  
const ButtonContained: any = styled(Button)({  
  margin: `28px 0px 0px 0px`,  
});
 
function SampleCard(props: SampleCardProps): JSX.Element {
  const {fns} = useSampleCard();
  return (
    <TypeQuest >
       <Image props={props} >
       </Image>
       <TextButton >
         <Content >
           <About >
             <Label >
               <Container >
                 <Typography >
                   <Label1 >
                     {`NEW`}
                       </Label1>
                 </Typography>
               </Container>
             </Label>
             <HotelName >
               {props.hotel.type}
                 </HotelName>
           </About>
           <Details >
             <Title >
               {props.hotel.name}
                 </Title>
             <Price >
               {props.hotel.price}
                 </Price>
           </Details>
           <Rating >
             <Icon1    fontSize = { "small"}  component = { StarBorderFilled1}/>
             <Rating1 >
               {props.hotel.rating}
                 </Rating1>
           </Rating>
           <Description >
             {props.hotel.description}
               </Description>
           {false &&
               <ButtonClicked >
               {`Button Clicked!`}
                 </ButtonClicked>
           }
           <ButtonContained variant="contained" size="large" color="primary"  onClick={fns.handleSubmit}  > Book ME </ButtonContained>
         </Content>
       </TextButton>
     </TypeQuest>
   );
}

export default SampleCard;
