/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { Button } from '@mui/material';
import QuestLogoImage from './assets/images/quest_logo.png';
import CompetitorLogoImage from './assets/images/competitor_logo.png';
import ActionsIconImage from './assets/images/Actions_Icon_7.png';
import ActionsIcon1Image from './assets/images/Actions_Icon_6.png';
import FigmaToCodeExportImage from './assets/images/Figma_to_Code_Export.png';
import SideImageImage from './assets/images/side_image_2.png';
import ActionsIcon2Image from './assets/images/Actions_Icon_5.png';
import SideImage1Image from './assets/images/side_image_1.png';
import ActionsIcon3Image from './assets/images/Actions_Icon_4.png';
import ActionsIcon4Image from './assets/images/Actions_Icon_3.png';
import SideImage2Image from './assets/images/side_image.png';
import QuestDesignSystemImage from './assets/images/Quest_Design_System.png';
import ActionsIcon5Image from './assets/images/Actions_Icon_2.png';
import ActionsIcon6Image from './assets/images/Actions_Icon_1.png';
import QuestLogoComparisonImage from './assets/images/Quest_logo_comparison.png';
import LogoAImage from './assets/images/logo_a.png';
import CheckmarkImage from './assets/images/checkmark_10.png';
import Checkmark1Image from './assets/images/checkmark_9.png';
import Checkmark2Image from './assets/images/checkmark_8.png';
import Checkmark3Image from './assets/images/checkmark_7.png';
import Checkmark4Image from './assets/images/checkmark_6.png';
import Checkmark5Image from './assets/images/checkmark_5.png';
import Checkmark6Image from './assets/images/checkmark_4.png';
import XMarkImage from './assets/images/x_mark_4.png';
import Checkmark7Image from './assets/images/checkmark_3.png';
import XMark1Image from './assets/images/x_mark_3.png';
import Checkmark8Image from './assets/images/checkmark_2.png';
import XMark2Image from './assets/images/x_mark_2.png';
import Checkmark9Image from './assets/images/checkmark_1.png';
import XMark3Image from './assets/images/x_mark_1.png';
import Checkmark10Image from './assets/images/checkmark.png';
import XMark4Image from './assets/images/x_mark.png';
import ActionsIcon7Image from './assets/images/Actions_Icon.png';
import { styled } from '@mui/material/styles';
import HeroImage from './assets/images/hero.png';
import DiscoverSecImage from './assets/images/Discover_Sec.png';
import CtaImage from './assets/images/CTA.png';

 
const Property1ReactPageD: any = styled("div")({  
  backgroundColor: `rgba(23, 23, 23, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  width: `1440px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
});
  
const Hero: any = styled("div")({  
  backgroundImage: `url(${HeroImage})`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `90px 100px 70px 100px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Logos: any = styled("div")({  
  backgroundColor: `rgba(0, 0, 0, 1)`,  
  border: `1px solid rgba(64, 64, 64, 1)`,  
  boxSizing: `border-box`,  
  borderRadius: `200px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `40px 60px`,  
  alignSelf: `stretch`,  
  height: `131px`,  
  margin: `0px`,  
});
  
const QuestLogo: any = styled("img")({  
  height: `81px`,  
  width: `81px`,  
  margin: `0px`,  
});
  
const Vs: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 0.9)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `900`,  
  fontSize: `42px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `34px`,  
  textTransform: `none`,  
  margin: `0px 0px 0px 36px`,  
});
  
const CompetitorLogo: any = styled("img")({  
  height: `58.97px`,  
  width: `51.54px`,  
  margin: `0px 0px 0px 36px`,  
});
  
const Frame126: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `40px 121px 0px 121px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const TakeDesignToLauncSpan1: any = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `68px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `64px`,  
  textTransform: `none`,  
});
  
const TakeDesignToLauncSpan2: any = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(129, 129, 129, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `68px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `64px`,  
  textTransform: `none`,  
});
  
const TakeDesignToLaunc: any = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `68px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `64px`,  
  textTransform: `none`,  
  textShadow: `0px 2px 4px rgba(0, 0, 0, 0.5)`,  
  margin: `0px`,  
});
  
const HeroAll: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `60px 0px 0px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const HeroContent: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const Subtitle: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const ActionsIcon: any = styled("img")({  
  height: `14px`,  
  width: `12.95px`,  
  margin: `0px`,  
});
  
const NeoFromQuestAiEm: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `2px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `uppercase`,  
  margin: `0px 0px 0px 6px`,  
});
  
const Title: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `0px 0px 10px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `18px 0px 0px 0px`,  
});
  
const TakeDesignToLaunc1: any = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `52px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `56px`,  
  textTransform: `none`,  
  width: `946px`,  
  margin: `0px`,  
});
  
const TakeDesignToLaunc2: any = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `42px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `56px`,  
  textTransform: `none`,  
  width: `946px`,  
  margin: `10px 0px 0px 0px`,  
});
  
const TakeDesignToLaunc3: any = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `52px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `56px`,  
  textTransform: `none`,  
  width: `946px`,  
  margin: `10px 0px 0px 0px`,  
});
  
const HeroSub: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `18px 0px 0px 0px`,  
});
  
const NeoFromQuestAiEm1: any = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `22px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `34px`,  
  textTransform: `none`,  
  width: `706px`,  
  margin: `0px`,  
});
  
const ButtonOutlined: any = styled(Button)({  
  margin: `34px 0px 0px 0px`,  
});
  
const Sec2: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `100px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Sec5Text: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `0px 30px 0px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  width: `466px`,  
  margin: `0px`,  
});
  
const Frame124: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const ActionsIcon1: any = styled("img")({  
  height: `14px`,  
  width: `14px`,  
  margin: `0px`,  
});
  
const NeoFromQuestAiEm2: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `2px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `uppercase`,  
  margin: `0px 0px 0px 10px`,  
});
  
const Frame165: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `22px 0px 0px 0px`,  
});
  
const TakeDesignToLaunc4: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `52px`,  
  letterSpacing: `-1px`,  
  textDecoration: `none`,  
  lineHeight: `52px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const NeoFromQuestAiEm3: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `16px 0px 0px 0px`,  
});
  
const FigmaToCodeExport: any = styled("img")({  
  height: `340px`,  
  width: `608px`,  
  margin: `0px 0px 0px 36px`,  
});
  
const Sec3: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `100px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Frame127: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const SideImage: any = styled("img")({  
  height: `331px`,  
  width: `453px`,  
  margin: `0px`,  
});
  
const Sec5Text1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 30px 0px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `32px 0px 0px 0px`,  
});
  
const Frame1241: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const ActionsIcon2: any = styled("img")({  
  height: `14px`,  
  width: `14px`,  
  margin: `0px`,  
});
  
const NeoFromQuestAiEm4: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `2px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `uppercase`,  
  margin: `0px 0px 0px 10px`,  
});
  
const Frame1651: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `22px 0px 0px 0px`,  
});
  
const TakeDesignToLaunc5: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `52px`,  
  letterSpacing: `-1px`,  
  textDecoration: `none`,  
  lineHeight: `52px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const NeoFromQuestAiEm5: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `16px 0px 0px 0px`,  
});
  
const Frame128: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px 0px 0px 211px`,  
});
  
const SideImage1: any = styled("img")({  
  height: `331px`,  
  width: `453px`,  
  margin: `0px`,  
});
  
const Sec5Text2: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 30px 0px 0px`,  
  boxSizing: `border-box`,  
  width: `454px`,  
  margin: `32px 0px 0px 0px`,  
});
  
const Frame1242: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const ActionsIcon3: any = styled("img")({  
  height: `14px`,  
  width: `14px`,  
  margin: `0px`,  
});
  
const NeoFromQuestAiEm6: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `2px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `uppercase`,  
  margin: `0px 0px 0px 10px`,  
});
  
const Frame1652: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `22px 0px 0px 0px`,  
});
  
const TakeDesignToLaunc6: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `52px`,  
  letterSpacing: `-1px`,  
  textDecoration: `none`,  
  lineHeight: `52px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const NeoFromQuestAiEm7: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `16px 0px 0px 0px`,  
});
  
const Sec4: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `100px 100px 176px 100px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Sec5Text3: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `0px 30px 0px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  width: `500px`,  
  margin: `0px`,  
});
  
const Frame1243: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const ActionsIcon4: any = styled("img")({  
  height: `14px`,  
  width: `14px`,  
  margin: `0px`,  
});
  
const NeoFromQuestAiEm8: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `2px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `uppercase`,  
  margin: `0px 0px 0px 10px`,  
});
  
const Frame1653: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `22px 0px 0px 0px`,  
});
  
const TakeDesignToLaunc7: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `52px`,  
  letterSpacing: `-1px`,  
  textDecoration: `none`,  
  lineHeight: `52px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const NeoFromQuestAiEm9: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `16px 0px 0px 0px`,  
});
  
const SideImage2: any = styled("img")({  
  height: `512px`,  
  width: `602px`,  
  margin: `0px 0px 0px 36px`,  
});
  
const Sec5: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `100px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const QuestDesignSystem: any = styled("img")({  
  height: `585px`,  
  width: `675px`,  
  margin: `0px`,  
});
  
const Sec5Text4: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `0px 30px 0px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  width: `466px`,  
  margin: `0px 0px 0px 56px`,  
});
  
const Frame1244: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const ActionsIcon5: any = styled("img")({  
  height: `14px`,  
  width: `14px`,  
  margin: `0px`,  
});
  
const NeoFromQuestAiEm10: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `2px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `uppercase`,  
  margin: `0px 0px 0px 10px`,  
});
  
const Frame1654: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `22px 0px 0px 0px`,  
});
  
const TakeDesignToLaunc8: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `52px`,  
  letterSpacing: `-1px`,  
  textDecoration: `none`,  
  lineHeight: `52px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const NeoFromQuestAiEm11: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `16px 0px 0px 0px`,  
});
  
const DiscoverSec: any = styled("div")({  
  backgroundImage: `url(${DiscoverSecImage})`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `90px 180px 126px 180px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Frame1271: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Subtitle1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const ActionsIcon6: any = styled("img")({  
  height: `14px`,  
  width: `12.95px`,  
  margin: `0px`,  
});
  
const NeoFromQuestAiEm12: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `2px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `uppercase`,  
  margin: `0px 0px 0px 6px`,  
});
  
const Title1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `24px 0px 0px 0px`,  
});
  
const TakeDesignToLaunc9: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `52px`,  
  letterSpacing: `-1px`,  
  textDecoration: `none`,  
  lineHeight: `50px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const TakeDesignToLaunc10: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `52px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `50px`,  
  textTransform: `none`,  
  background: `linear-gradient(-90deg, rgba(254, 136, 136, 1) -1.9975096989239764e-12%, rgba(128, 102, 255, 1) 74.49799203920163%)`,  
  backgroundClip: `text`,  
  WebkitBackgroundClip: `text`,  
  WebkitTextFillColor: `transparent`,  
  margin: `0px 0px 0px 10px`,  
});
  
const ImportYourDifferen: any = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `none`,  
  width: `672px`,  
  margin: `24px 0px 0px 0px`,  
});
  
const ButtonOutlined1: any = styled(Button)({  
  margin: `24px 0px 0px 0px`,  
});
  
const CompareSec: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `100px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Compare: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `706px`,  
  margin: `0px`,  
});
  
const Frame125: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 20px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const TakeDesignToLaunc11: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `52px`,  
  letterSpacing: `-1px`,  
  textDecoration: `none`,  
  lineHeight: `50px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const TakeDesignToLaunc12: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `52px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `54px`,  
  textTransform: `none`,  
  background: `linear-gradient(-90deg, rgba(254, 136, 136, 1) 27.16229514331244%, rgba(128, 102, 255, 1) 97.86200295926109%)`,  
  backgroundClip: `text`,  
  WebkitBackgroundClip: `text`,  
  WebkitTextFillColor: `transparent`,  
  width: `641.49px`,  
  margin: `0px`,  
});
  
const CompareChart: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-end`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `706px`,  
  margin: `24px 0px 0px 0px`,  
});
  
const Frame122: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Row: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Frame1221: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Fpo: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 0)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  width: `241px`,  
  height: `61px`,  
  margin: `0px`,  
});
  
const Frame1222: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 75px`,  
});
  
const QuestLogoComparison: any = styled("img")({  
  height: `44px`,  
  width: `151.5px`,  
});
  
const LogoA: any = styled("img")({  
  height: `34px`,  
  width: `115.22px`,  
});
  
const Row1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const Divider: any = styled("div")({  
  backgroundColor: `rgba(88, 88, 88, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `2px`,  
  margin: `0px`,  
});
  
const Frame1223: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `10px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const NeoFromQuestAiEm13: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  width: `241px`,  
  height: `24px`,  
  margin: `0px`,  
});
  
const Frame1224: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `0px 30px 0px 70px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 75px`,  
});
  
const Checkmark: any = styled("img")({  
  height: `40px`,  
  width: `40px`,  
});
  
const Checkmark1: any = styled("img")({  
  height: `40px`,  
  width: `40px`,  
});
  
const Row2: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const Divider1: any = styled("div")({  
  backgroundColor: `rgba(88, 88, 88, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `2px`,  
  margin: `0px`,  
});
  
const Frame1225: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `10px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const NeoFromQuestAiEm14: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  width: `241px`,  
  height: `24px`,  
  margin: `0px`,  
});
  
const Frame1226: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `0px 30px 0px 70px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 75px`,  
});
  
const Checkmark2: any = styled("img")({  
  height: `40px`,  
  width: `40px`,  
});
  
const Checkmark3: any = styled("img")({  
  height: `40px`,  
  width: `40px`,  
});
  
const Row3: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const Divider2: any = styled("div")({  
  backgroundColor: `rgba(88, 88, 88, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `2px`,  
  margin: `0px`,  
});
  
const Frame1227: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `10px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const NeoFromQuestAiEm15: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  width: `241px`,  
  height: `48px`,  
  margin: `0px`,  
});
  
const Frame1228: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `0px 30px 0px 70px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 75px`,  
});
  
const Checkmark4: any = styled("img")({  
  height: `40px`,  
  width: `40px`,  
});
  
const Checkmark5: any = styled("img")({  
  height: `40px`,  
  width: `40px`,  
});
  
const Row4: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const Divider3: any = styled("div")({  
  backgroundColor: `rgba(88, 88, 88, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `2px`,  
  margin: `0px`,  
});
  
const Frame1229: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `10px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const NeoFromQuestAiEm16: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  width: `241px`,  
  height: `48px`,  
  margin: `0px`,  
});
  
const Frame12210: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `0px 30px 0px 70px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 75px`,  
});
  
const Checkmark6: any = styled("img")({  
  height: `40px`,  
  width: `40px`,  
});
  
const XMark: any = styled("img")({  
  height: `40.01px`,  
  width: `40.01px`,  
});
  
const Row5: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const Divider4: any = styled("div")({  
  backgroundColor: `rgba(88, 88, 88, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `2px`,  
  margin: `0px`,  
});
  
const Frame12211: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `10px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const NeoFromQuestAiEm17: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  width: `241px`,  
  height: `24px`,  
  margin: `0px`,  
});
  
const Frame12212: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `0px 30px 0px 70px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 75px`,  
});
  
const Checkmark7: any = styled("img")({  
  height: `40px`,  
  width: `40px`,  
});
  
const XMark1: any = styled("img")({  
  height: `40.01px`,  
  width: `40.01px`,  
});
  
const Row6: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const Divider5: any = styled("div")({  
  backgroundColor: `rgba(88, 88, 88, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `2px`,  
  margin: `0px`,  
});
  
const Frame12213: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `10px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const NeoFromQuestAiEm18: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  width: `241px`,  
  height: `48px`,  
  margin: `0px`,  
});
  
const Frame12214: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `0px 30px 0px 70px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 75px`,  
});
  
const Checkmark8: any = styled("img")({  
  height: `40px`,  
  width: `40px`,  
});
  
const XMark2: any = styled("img")({  
  height: `40.01px`,  
  width: `40.01px`,  
});
  
const Row7: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const Divider6: any = styled("div")({  
  backgroundColor: `rgba(88, 88, 88, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `2px`,  
  margin: `0px`,  
});
  
const Frame12215: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `10px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const NeoFromQuestAiEm19: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  width: `241px`,  
  height: `48px`,  
  margin: `0px`,  
});
  
const Frame12216: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `0px 30px 0px 70px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 75px`,  
});
  
const Checkmark9: any = styled("img")({  
  height: `40px`,  
  width: `40px`,  
});
  
const XMark3: any = styled("img")({  
  height: `40.01px`,  
  width: `40.01px`,  
});
  
const Row8: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const Divider7: any = styled("div")({  
  backgroundColor: `rgba(88, 88, 88, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `2px`,  
  margin: `0px`,  
});
  
const Frame12217: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `10px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const NeoFromQuestAiEm20: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  width: `241px`,  
  height: `48px`,  
  margin: `0px`,  
});
  
const Frame12218: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `0px 30px 0px 70px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 75px`,  
});
  
const Checkmark10: any = styled("img")({  
  height: `40px`,  
  width: `40px`,  
});
  
const XMark4: any = styled("img")({  
  height: `40.01px`,  
  width: `40.01px`,  
});
  
const Cta: any = styled("div")({  
  backgroundImage: `url(${CtaImage})`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `111px 180px 200px 180px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const TryRiskFree: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `400px`,  
  margin: `0px`,  
});
  
const Sec4Text: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const Subtitle2: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const ActionsIcon7: any = styled("img")({  
  height: `14px`,  
  width: `14px`,  
  margin: `0px`,  
});
  
const NewWay: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `2px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `uppercase`,  
  width: `417px`,  
  margin: `0px 0px 0px 8px`,  
});
  
const TryItHeadline: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `24px 0px 0px 0px`,  
});
  
const Frame1251: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `442px`,  
  margin: `0px`,  
});
  
const TakeDesignToLaunc13: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `44px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `42px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const TakeDesignToLaunc14: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `44px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `42px`,  
  textTransform: `none`,  
  background: `linear-gradient(-90deg, rgba(254, 136, 136, 1) 27.16229514331245%, rgba(128, 102, 255, 1) 97.86200295926109%)`,  
  backgroundClip: `text`,  
  WebkitBackgroundClip: `text`,  
  WebkitTextFillColor: `transparent`,  
  width: `297px`,  
  margin: `0px 0px 0px 8px`,  
});
  
const TakeDesignToLaunc15: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `44px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `42px`,  
  textTransform: `none`,  
  width: `442px`,  
  margin: `0px`,  
});
  
const NeoFromQuestAiEm21: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `18px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `24px 0px 0px 0px`,  
});
  
const ButtonOutlined2: any = styled(Button)({  
  margin: `24px 0px 0px 0px`,  
});
 
function VsAnima(): JSX.Element {
  return (
    <Property1ReactPageD >
       <Hero >
         <Logos >
           <QuestLogo  src={QuestLogoImage} alt={"quest_logo"}/>
           <Vs >
             {`VS`}
               </Vs>
           <CompetitorLogo  src={CompetitorLogoImage} alt={"competitor logo"}/>
         </Logos>
         <Frame126 >
           <TakeDesignToLaunc >
             <TakeDesignToLauncSpan1  >{`Quest vs `}</TakeDesignToLauncSpan1>
             <TakeDesignToLauncSpan2  >{`Anima`}</TakeDesignToLauncSpan2>
           </TakeDesignToLaunc>
         </Frame126>
         <HeroAll >
           <HeroContent >
             <Subtitle >
               <ActionsIcon  src={ActionsIconImage} alt={"Actions Icon"}/>
               <NeoFromQuestAiEm >
                 {`FUNDAMENTALLY DIFFERENT`}
                   </NeoFromQuestAiEm>
             </Subtitle>
             <Title >
               <TakeDesignToLaunc1 >
                 {`Anima gives you prototype-quality code.`}
                   </TakeDesignToLaunc1>
               <TakeDesignToLaunc2 >
                 {`vs`}
                   </TakeDesignToLaunc2>
               <TakeDesignToLaunc3 >
                 {`Quest gives true production-quality code.`}
                   </TakeDesignToLaunc3>
             </Title>
             <HeroSub >
               <NeoFromQuestAiEm1 >
                 {`Both Quest & Anima convert design into code. Both start with Figma, then bring design into a web editor and allow you to export code from there. However, Quest is the new standard in building frontend for your React apps. Quest gives you clean, extendable components so you can easily build what you want.`}
                   </NeoFromQuestAiEm1>
               <ButtonOutlined variant="outlined" size="large" color="primary"    > Sign Up Now </ButtonOutlined>
             </HeroSub>
           </HeroContent>
         </HeroAll>
       </Hero>
       <Sec2 >
         <Sec5Text >
           <Frame124 >
             <ActionsIcon1  src={ActionsIcon1Image} alt={"Actions Icon"}/>
             <NeoFromQuestAiEm2 >
               {`READY FOR PRODUCTION`}
                 </NeoFromQuestAiEm2>
           </Frame124>
           <Frame165 >
             <TakeDesignToLaunc4 >
               {`Clean, production ready code`}
                 </TakeDesignToLaunc4>
             <NeoFromQuestAiEm3 >
               {`Quest gives your team production ready code that is extendable. Anima was built primarily as a prototyping tool, so their generated code requires additional manual effort to make production ready must be redone if design gets changed.`}
                 </NeoFromQuestAiEm3>
           </Frame165>
         </Sec5Text>
         <FigmaToCodeExport  src={FigmaToCodeExportImage} alt={"Figma to Code Export"}/>
       </Sec2>
       <Sec3 >
         <Frame127 >
           <SideImage  src={SideImageImage} alt={"side image"}/>
           <Sec5Text1 >
             <Frame1241 >
               <ActionsIcon2  src={ActionsIcon2Image} alt={"Actions Icon"}/>
               <NeoFromQuestAiEm4 >
                 {`KEEP YOUR WORKFLOW`}
                   </NeoFromQuestAiEm4>
             </Frame1241>
             <Frame1651 >
               <TakeDesignToLaunc5 >
                 {`Keep the workflows that you love`}
                   </TakeDesignToLaunc5>
               <NeoFromQuestAiEm5 >
                 {`Designers can continue to build in Figma, and developers can continue to use their favorite tools from code editors to the rest of the CI/CD pipeline (VS Code plugin coming soon). Teams don’t need to fundamentally change what they do or learn a tool that interupts their flow. `}
                   </NeoFromQuestAiEm5>
             </Frame1651>
           </Sec5Text1>
         </Frame127>
         <Frame128 >
           <SideImage1  src={SideImage1Image} alt={"side image"}/>
           <Sec5Text2 >
             <Frame1242 >
               <ActionsIcon3  src={ActionsIcon3Image} alt={"Actions Icon"}/>
               <NeoFromQuestAiEm6 >
                 {`ITERATE FREELY`}
                   </NeoFromQuestAiEm6>
             </Frame1242>
             <Frame1652 >
               <TakeDesignToLaunc6 >
                 {`Separation of concerns`}
                   </TakeDesignToLaunc6>
               <NeoFromQuestAiEm7 >
                 {`Quest generates separate files for presentation and business logic, so teams can work independently without overriding each other's work.`}
                   </NeoFromQuestAiEm7>
             </Frame1652>
           </Sec5Text2>
         </Frame128>
       </Sec3>
       <Sec4 >
         <Sec5Text3 >
           <Frame1243 >
             <ActionsIcon4  src={ActionsIcon4Image} alt={"Actions Icon"}/>
             <NeoFromQuestAiEm8 >
               {`COPY AND PASTE COMPONENTS`}
                 </NeoFromQuestAiEm8>
           </Frame1243>
           <Frame1653 >
             <TakeDesignToLaunc7 >
               {`Native support for MUI`}
                 </TakeDesignToLaunc7>
             <NeoFromQuestAiEm9 >
               {`Quest natively supports MUI. Simply style your components inside the MUI Figma file and copy and paste your components into your custom design. When you export custom designs into Quest, you’ll get working, real versions you can interact with inside Quest. Support for other component libraries coming soon.`}
                 </NeoFromQuestAiEm9>
           </Frame1653>
         </Sec5Text3>
         <SideImage2  src={SideImage2Image} alt={"side image"}/>
       </Sec4>
       <Sec5 >
         <QuestDesignSystem  src={QuestDesignSystemImage} alt={"Quest Design System"}/>
         <Sec5Text4 >
           <Frame1244 >
             <ActionsIcon5  src={ActionsIcon5Image} alt={"Actions Icon"}/>
             <NeoFromQuestAiEm10 >
               {`CUSTOMIZED FOR YOUR BRAND`}
                 </NeoFromQuestAiEm10>
           </Frame1244>
           <Frame1654 >
             <TakeDesignToLaunc8 >
               {`Full support for design systems`}
                 </TakeDesignToLaunc8>
             <NeoFromQuestAiEm11 >
               {`Quest works with the MUI design system or even your own. Easily sync your design system to Quest for use in with your React App or use your own components that can be linked to your own design system.`}
                 </NeoFromQuestAiEm11>
           </Frame1654>
         </Sec5Text4>
       </Sec5>
       <DiscoverSec >
         <Frame1271 >
           <Subtitle1 >
             <ActionsIcon6  src={ActionsIcon6Image} alt={"Actions Icon"}/>
             <NeoFromQuestAiEm12 >
               {`THE FUTURE of frontend`}
                 </NeoFromQuestAiEm12>
           </Subtitle1>
           <Title1 >
             <TakeDesignToLaunc9 >
               {`Our`}
                 </TakeDesignToLaunc9>
             <TakeDesignToLaunc10 >
               {`philosophy`}
                 </TakeDesignToLaunc10>
           </Title1>
           <ImportYourDifferen >
             {`Quest is here to change the way teams build, not just incrementally improve it. Most nocode tools and design-to-code tools ask you to throw away what you have and start over with new skills and processes. Quest’s goal is to help you build faster and better using your team’s own skills and workflow. Your team will become a pro at Quest in 15 minutes but it’ll save weeks of development time. You can use Quest to build your MVP or just simply add new components to your existing product.`}
               </ImportYourDifferen>
           <ButtonOutlined1 variant="outlined" size="large" color="primary"    > Sign Up Now </ButtonOutlined1>
         </Frame1271>
       </DiscoverSec>
       <CompareSec >
         <Compare >
           <Frame125 >
             <TakeDesignToLaunc11 >
               {`Built for the most demanding`}
                 </TakeDesignToLaunc11>
             <TakeDesignToLaunc12 >
               {`product teams `}
                 </TakeDesignToLaunc12>
           </Frame125>
           <CompareChart >
             <Frame122 >
               <Row >
                 <Frame1221 >
                   <Fpo >
                     {`Build new applications`}
                       </Fpo>
                   <Frame1222 >
                     <QuestLogoComparison  src={QuestLogoComparisonImage} alt={"Quest logo comparison"}/>
                     <LogoA  src={LogoAImage} alt={"logo a"}/>
                   </Frame1222>
                 </Frame1221>
               </Row>
               <Row1 >
                 <Divider >
                 </Divider>
                 <Frame1223 >
                   <NeoFromQuestAiEm13 >
                     {`Build new applications`}
                       </NeoFromQuestAiEm13>
                   <Frame1224 >
                     <Checkmark  src={CheckmarkImage} alt={"checkmark"}/>
                     <Checkmark1  src={Checkmark1Image} alt={"checkmark"}/>
                   </Frame1224>
                 </Frame1223>
               </Row1>
               <Row2 >
                 <Divider1 >
                 </Divider1>
                 <Frame1225 >
                   <NeoFromQuestAiEm14 >
                     {`Generates react.js code`}
                       </NeoFromQuestAiEm14>
                   <Frame1226 >
                     <Checkmark2  src={Checkmark2Image} alt={"checkmark"}/>
                     <Checkmark3  src={Checkmark3Image} alt={"checkmark"}/>
                   </Frame1226>
                 </Frame1225>
               </Row2>
               <Row3 >
                 <Divider2 >
                 </Divider2>
                 <Frame1227 >
                   <NeoFromQuestAiEm15 >
                     {`Integrates with the design and dev tools you love`}
                       </NeoFromQuestAiEm15>
                   <Frame1228 >
                     <Checkmark4  src={Checkmark4Image} alt={"checkmark"}/>
                     <Checkmark5  src={Checkmark5Image} alt={"checkmark"}/>
                   </Frame1228>
                 </Frame1227>
               </Row3>
               <Row4 >
                 <Divider3 >
                 </Divider3>
                 <Frame1229 >
                   <NeoFromQuestAiEm16 >
                     {`Add to existing applications easily`}
                       </NeoFromQuestAiEm16>
                   <Frame12210 >
                     <Checkmark6  src={Checkmark6Image} alt={"checkmark"}/>
                     <XMark  src={XMarkImage} alt={"x mark"}/>
                   </Frame12210>
                 </Frame1229>
               </Row4>
               <Row5 >
                 <Divider4 >
                 </Divider4>
                 <Frame12211 >
                   <NeoFromQuestAiEm17 >
                     {`Design system support built-in`}
                       </NeoFromQuestAiEm17>
                   <Frame12212 >
                     <Checkmark7  src={Checkmark7Image} alt={"checkmark"}/>
                     <XMark1  src={XMark1Image} alt={"x mark"}/>
                   </Frame12212>
                 </Frame12211>
               </Row5>
               <Row6 >
                 <Divider5 >
                 </Divider5>
                 <Frame12213 >
                   <NeoFromQuestAiEm18 >
                     {`Component library support built-in (MUI)`}
                       </NeoFromQuestAiEm18>
                   <Frame12214 >
                     <Checkmark8  src={Checkmark8Image} alt={"checkmark"}/>
                     <XMark2  src={XMark2Image} alt={"x mark"}/>
                   </Frame12214>
                 </Frame12213>
               </Row6>
               <Row7 >
                 <Divider6 >
                 </Divider6>
                 <Frame12215 >
                   <NeoFromQuestAiEm19 >
                     {`Clean code with separation of concerns`}
                       </NeoFromQuestAiEm19>
                   <Frame12216 >
                     <Checkmark9  src={Checkmark9Image} alt={"checkmark"}/>
                     <XMark3  src={XMark3Image} alt={"x mark"}/>
                   </Frame12216>
                 </Frame12215>
               </Row7>
               <Row8 >
                 <Divider7 >
                 </Divider7>
                 <Frame12217 >
                   <NeoFromQuestAiEm20 >
                     {`Generates production-ready code`}
                       </NeoFromQuestAiEm20>
                   <Frame12218 >
                     <Checkmark10  src={Checkmark10Image} alt={"checkmark"}/>
                     <XMark4  src={XMark4Image} alt={"x mark"}/>
                   </Frame12218>
                 </Frame12217>
               </Row8>
             </Frame122>
           </CompareChart>
         </Compare>
       </CompareSec>
       <Cta >
         <TryRiskFree >
           <Sec4Text >
             <Subtitle2 >
               <ActionsIcon7  src={ActionsIcon7Image} alt={"Actions Icon"}/>
               <NewWay >
                 {`SCALES WHEN READY`}
                   </NewWay>
             </Subtitle2>
             <TryItHeadline >
               <Frame1251 >
                 <TakeDesignToLaunc13 >
                   {`Try it`}
                     </TakeDesignToLaunc13>
                 <TakeDesignToLaunc14 >
                   {`risk-free`}
                     </TakeDesignToLaunc14>
               </Frame1251>
               <TakeDesignToLaunc15 >
                 {`and see for yourself`}
                   </TakeDesignToLaunc15>
             </TryItHeadline>
             <NeoFromQuestAiEm21 >
               {`Component plans include a 30-day trial. `}
                 </NeoFromQuestAiEm21>
             <ButtonOutlined2 variant="outlined" size="large" color="primary"    > Sign Up Now </ButtonOutlined2>
           </Sec4Text>
         </TryRiskFree>
       </Cta>
     </Property1ReactPageD>
   );
}

export default VsAnima;
